name: fadelive
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - ipywidgets
  - jupyterlab
  - matplotlib
  - networkx
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - umap-learn
  - wordcloud
 
  - pip:
      - adjustText
      - gensim
      - HanTa
      - nltk
      - plotly
      - pyvis
      - spacy>=3.8
