name: fadelive
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - ipywidgets
  - jupyterlab
  - matplotlib
  - networkx
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - umap-learn
  - wordcloud
 
  - pip:
      - adjustText
      - gensim
      - HanTa
      - nltk
      - plotly
      - pyvis
      - spacy>=3.8
      - "de-core-news-lg @ https://github.com/explosion/spacy-models/releases/download/de_core_news_lg-3.8.0/de_core_news_lg-3.8.0-py3-none-any.whl"
