[project]
name = "fadelive"
version = "1.2.0"
description =   "Ger: fadelive: Setup von NLP, Text Mining und Visualisierungen eines bildungshistorischen Korpus zur Vermittlung des Deutschunterrichts an höheren Schulen im 19. Jahrhundert in Deutschland. Eng: fadelive: Setup of NLP, text mining tools and visualisations of an educational history corpus for teaching German in secondary schools in 19th-century Germany."

readme = "README.md"
requires-python = ">=3.11"

authors = [
    { name = "Hendrick Heimböckel" }
]

license = { file = "LICENSE" }

dependencies = [
    "adjustText",
    "gensim",
    "HanTa",
    "ipykernel",
    "ipywidgets",
    "matplotlib",
    "networkx",
    "nltk",
    "numpy",
    "pandas",
    "plotly",
    "pyvis",
    "scikit-learn",
    "scipy",
    "seaborn",
    "spacy>=3.8",
    "tqdm",
    "umap-learn",
    "wordcloud"
]

[project.urls]
repository = "https://github.com/deinuser/text-mining-projekt"
documentation = "https://doi.org/10.25625/APN9VH"

[project.scripts]
fadelive = "fadelive.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"